# Generated by Django 4.2.3 on 2023-07-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_product_is_active_productline"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="vdfvdfvd", max_length=255),
            preserve_default=False,
        ),
    ]
