# Generated by Django 4.2.3 on 2023-07-24 00:19

from django.db import migrations
import product.fields


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_brand_is_active_category_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="order",
            field=product.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
