# Generated by Django 4.2.3 on 2023-07-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_productline_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="dfgdfghe", max_length=255),
            preserve_default=False,
        ),
    ]
